# assumes that you have done
# git clone https://github.com/google/draco/
# cd draco
# mkdir build
# cd build
# cmake ..

dracodir="../../3d/draco"
files=scan(file.path(dracodir, "/build/CMakeFiles/dracodec.dir/link.txt"), what="")

ofiles=grep(".cc.o$", files, value = T)
other=grep(".cc.o$", files, value = T, invert = T)

ccfiles=sub(".cc.o$",".cc", ofiles)
ccfiles=sub(".*/src/","src/", ccfiles)

ccfiles=grep("CMakeFiles", ccfiles, value = T, invert = T)

inpath=file.path(dracodir, ccfiles)
stopifnot(all(file.exists(inpath)))

file.copy(inpath, 'src')

findhfiles <- function(cfile) {
  l=readLines(cfile)
  includes=grep('^#include "draco', l, value=T)
  hfiles=stringr::str_match(includes, '"([^"]+)"')[,2]
  hfiles
}

localccfiles=file.path('src', basename(ccfiles))
# find headers referenced in c files
allhfiles=sapply(localccfiles, findhfiles)
allgood=all(sapply(allhfiles, function(x) all(!is.na(x))))
stopifnot(allgood)
hfiles=unique(unlist(allhfiles))
# special file generated by cmake
hfiles=grep("draco_features.h", hfiles, value = T, invert = T)

allhfiles2=sapply(file.path(dracodir, 'src', hfiles), findhfiles)
allgood=all(sapply(allhfiles2, function(x) all(!is.na(x))))
stopifnot(allgood)
hfiles2=unique(unlist(allhfiles2))
hfiles=c(hfiles2, hfiles)
hfiles=grep("draco_features.h", hfiles, value = T, invert = T)


allhfiles3=sapply(file.path(dracodir, 'src', hfiles), findhfiles)
allgood=all(sapply(allhfiles3, function(x) all(!is.na(x))))
stopifnot(allgood)
hfiles3=unique(unlist(allhfiles3))
hfiles=c(hfiles3, hfiles)
hfiles=grep("draco_features.h", hfiles, value = T, invert = T)

file.copy(file.path(dracodir, "build/draco/draco_features.h"), "src/draco")

inpath=file.path(dracodir, 'src', hfiles)
stopifnot(all(file.exists(inpath)))

srcsubdirs=unique(dirname(file.path('src', hfiles)))
sapply(srcsubdirs,dir.create, recursive = T)

file.copy(inpath, file.path('src', hfiles))
