# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dracodecode <- function(data, index_offset = 1L) {
    .Call(`_dracor_dracodecode`, data, index_offset)
}

dracoencode <- function(vertices, faces, num_vertices, num_faces) {
    invisible(.Call(`_dracor_dracoencode`, vertices, faces, num_vertices, num_faces))
}

timesTwo <- function(x) {
    .Call(`_dracor_timesTwo`, x)
}

